In [22]:
import pandas as pd

In [23]:
# example web scrap of FBref data table 

df = pd.read_html('https://fbref.com/en/comps/189/possesion/Womens-Super-League-Stats')

In [24]:
for idx, table in enumerate(df):
    print('***************************')
    print(idx)
    print(table)

***************************
0
    Rk            Squad  MP   W  D   L  GF  GA  GD  Pts  Pts/MP    xG   xGA  \
0    1          Chelsea  15  12  1   2  45  13  32   37    2.47  37.5  13.6
1    2  Manchester City  15  12  1   2  38   9  29   37    2.47  29.5  12.6
2    3          Arsenal  15  11  1   3  33  14  19   34    2.27  34.7  10.9
3    4   Manchester Utd  15   7  4   4  32  19  13   25    1.67  26.4  17.0
4    5        Liverpool  15   7  4   4  22  20   2   25    1.67  16.4  19.6
5    6        Tottenham  15   5  4   6  21  29  -8   19    1.27  16.6  23.1
6    7   Leicester City  15   4  4   7  21  30  -9   16    1.07  17.3  29.8
7    8      Aston Villa  15   5  1   9  19  31 -12   16    1.07  18.7  23.9
8    9         Brighton  15   4  2   9  20  33 -13   14    0.93  14.2  29.9
9   10          Everton  15   4  2   9  13  27 -14   14    0.93  14.4  25.0
10  11         West Ham  15   3  3   9  16  30 -14   12    0.80  16.4  20.6
11  12     Bristol City  15   1  3  11  20  45 -25    6    0.40  12.4  28.5

     xGD  xGD/90     Last 5  Attendance  \
0   24.0    1.60  W W W L W        4637
1   16.8    1.12  W W W W W        3114
2   23.7    1.58  W W L W W       35006
3    9.4    0.63  L W W L D       11134
4   -3.2   -0.21  L L D W W        5229
5   -6.5   -0.44  W L D L L        3902
6  -12.5   -0.84  L W L W L        1531
7   -5.2   -0.35  W L D W L        4379
8  -15.7   -1.05  W L L L W        3494
9  -10.5   -0.70  L L L W L        1011
10  -4.2   -0.28  L W W L D        4479
11 -16.1   -1.07  L L D L L        7687

                                  Top Team Scorer            Goalkeeper  Notes
0                               Lauren James - 12        Hannah Hampton    NaN
1                               Khadija Shaw - 15        Khiara Keating    NaN
2                               Alessia Russo - 6    Manuela Zinsberger    NaN
3                               Nikita Parris - 8            Mary Earps    NaN
4   Sophie Román Haug, Marie-Therese Höbinger - 4          Rachael Laws    NaN
5                               Martha Thomas - 7       Rebecca Spencer    NaN
6                               Jutta Rantala - 5        Janina Leitzig    NaN
7                                 Rachel Daly - 6  Daphne van Domselaar    NaN
8                          Elisabeth Terland - 11       Sophie Baggaley    NaN
9                Aurora Galli, Megan Finnigan - 3      Courtney Brosnan    NaN
10                             Viviane Asseyi - 6      Mackenzie Arnold    NaN
11                            Amalie Thestrup - 9          Olivia Clark    NaN
***************************
1
   Unnamed: 0_level_0 Unnamed: 1_level_0 Home                           ...  \
                   Rk              Squad   MP  W  D  L  GF  GA  GD Pts  ...
0                   1            Chelsea    8  7  0  1  24   8  16  21  ...
1                   2    Manchester City    8  6  1  1  24   5  19  19  ...
2                   3            Arsenal    8  7  0  1  17   6  11  21  ...
3                   4     Manchester Utd    7  3  2  2  14   9   5  11  ...
4                   5          Liverpool    7  3  2  2  10   6   4  11  ...
5                   6          Tottenham    7  2  2  3   7  11  -4   8  ...
6                   7     Leicester City    8  2  2  4  10  16  -6   8  ...
7                   8        Aston Villa    7  1  1  5   8  20 -12   4  ...
8                   9           Brighton    8  1  2  5   8  18 -10   5  ...
9                  10            Everton    7  1  1  5   6  17 -11   4  ...
10                 11           West Ham    8  1  2  5  11  16  -5   5  ...
11                 12       Bristol City    7  0  0  7   7  22 -15   0  ...

   Away
      L  GF  GA  GD Pts Pts/MP    xG   xGA   xGD xGD/90
0     1  21   5  16  16   2.29  15.6   5.9   9.7   1.39
1     1  14   4  10  18   2.57  11.4   7.3   4.1   0.58
2     2  16   8   8  13   1.86  18.3   4.7  13.6   1.94
3     2  18  10   8  14   1.75  15.5  10.0   5.5   0.69
4     2  12  14  -2  14   1.75   8.5  13.4  -4.9  -0.61
5     3  14  18  -4  11   1.38   9.6  13.2  -3.6  -0.45
6     3  11  14  -3   8   1.14   5.1  12.0  -6.8  -0.98
7     4  11  11   0  12   1.50   7.3  11.6  -4.2  -0.53
8     4  12  15  -3   9   1.29   6.9  16.5  -9.6  -1.37
9     4   7  10  -3  10   1.25   7.1  15.4  -8.2  -1.03
10    4   5  14  -9   7   1.00   7.1   8.9  -1.8  -0.26
11    4  13  23 -10   6   0.75   7.6  15.3  -7.7  -0.96

[12 rows x 28 columns]
***************************
2
   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                Squad               # Pl                Age
0             Arsenal                 24               28.2
1         Aston Villa                 23               28.3
2            Brighton                 21               27.5
3        Bristol City                 30               24.5
4             Chelsea                 28               27.3
5             Everton                 26               26.3
6      Leicester City                 24               27.2
7           Liverpool                 23               27.1
8     Manchester City                 22               25.9
9      Manchester Utd                 19               27.3
10          Tottenham                 27               27.5
11           West Ham                 25               27.0

   Unnamed: 3_level_0 Playing Time                    Performance      ...  \
                 Poss           MP Starts   Min   90s         Gls Ast  ...
0                58.5           15    165  1350  15.0          32  23  ...
1                53.9           15    165  1350  15.0          18  10  ...
2                44.3           15    165  1350  15.0          20  14  ...
3                33.7           15    165  1350  15.0          20   9  ...
4                60.2           15    165  1350  15.0          44  31  ...
5                44.3           15    165  1350  15.0          12   7  ...
6                50.8           15    165  1350  15.0          21  16  ...
7                46.8           15    165  1350  15.0          20  15  ...
8                59.1           15    165  1350  15.0          36  26  ...
9                56.7           15    165  1350  15.0          32  23  ...
10               48.3           15    165  1350  15.0          21  13  ...
11               43.4           15    165  1350  15.0          16   7  ...

   Per 90 Minutes
              Gls   Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG
0            2.13  1.53  3.67  2.00   3.53  2.31  1.64   3.95  2.15     3.79
1            1.20  0.67  1.87  1.00   1.67  1.25  0.78   2.03  1.09     1.87
2            1.33  0.93  2.27  1.27   2.20  0.94  0.69   1.64  0.89     1.59
3            1.33  0.60  1.93  1.20   1.80  0.83  0.42   1.25  0.72     1.14
4            2.93  2.07  5.00  2.80   4.87  2.50  1.89   4.39  2.40     4.28
5            0.80  0.47  1.27  0.67   1.13  0.96  0.60   1.56  0.82     1.43
6            1.40  1.07  2.47  1.40   2.47  1.15  0.85   2.00  1.15     2.00
7            1.33  1.00  2.33  1.33   2.33  1.09  0.88   1.97  1.09     1.97
8            2.40  1.73  4.13  2.33   4.07  1.96  1.26   3.23  1.80     3.06
9            2.13  1.53  3.67  2.07   3.60  1.76  1.29   3.05  1.71     3.01
10           1.40  0.87  2.27  1.40   2.27  1.11  0.77   1.87  1.11     1.87
11           1.07  0.47  1.53  0.87   1.33  1.09  0.57   1.67  0.94     1.51

[12 rows x 32 columns]
***************************
3
    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                 Squad               # Pl                Age
0           vs Arsenal                 24               27.1
1       vs Aston Villa                 23               26.8
2          vs Brighton                 21               26.8
3      vs Bristol City                 30               27.4
4           vs Chelsea                 28               26.9
5           vs Everton                 26               27.0
6    vs Leicester City                 24               26.5
7         vs Liverpool                 23               27.2
8   vs Manchester City                 22               27.0
9    vs Manchester Utd                 19               27.3
10        vs Tottenham                 27               27.2
11         vs West Ham                 25               27.0

   Unnamed: 3_level_0 Playing Time                    Performance      ...  \
                 Poss           MP Starts   Min   90s         Gls Ast  ...
0                41.5           15    165  1350  15.0          14  12  ...
1                46.1           15    165  1350  15.0          30  17  ...
2                55.7           15    165  1350  15.0          33  20  ...
3                66.3           15    165  1350  15.0          44  25  ...
4                39.8           15    165  1350  15.0          12   7  ...
5                55.7           15    165  1350  15.0          27  22  ...
6                49.2           15    165  1350  15.0          29  20  ...
7                53.2           15    165  1350  15.0          19  12  ...
8                40.9           15    165  1350  15.0           9   5  ...
9                43.3           15    165  1350  15.0          17  12  ...
10               51.7           15    165  1350  15.0          28  20  ...
11               56.6           15    165  1350  15.0          30  22  ...

   Per 90 Minutes
              Gls   Ast   G+A  G-PK G+A-PK    xG   xAG xG+xAG  npxG npxG+xAG
0            0.93  0.80  1.73  0.87   1.67  0.73  0.57   1.30  0.68     1.25
1            2.00  1.13  3.13  1.87   3.00  1.60  1.11   2.70  1.49     2.60
2            2.20  1.33  3.53  2.20   3.53  1.99  1.54   3.53  1.99     3.53
3            2.93  1.67  4.60  2.80   4.47  1.90  1.16   3.06  1.80     2.96
4            0.80  0.47  1.27  0.73   1.20  0.90  0.60   1.50  0.85     1.45
5            1.80  1.47  3.27  1.67   3.13  1.66  1.18   2.84  1.50     2.68
6            1.93  1.33  3.27  1.87   3.20  1.99  1.35   3.34  1.88     3.23
7            1.27  0.80  2.07  1.13   1.93  1.31  0.88   2.18  1.20     2.08
8            0.60  0.33  0.93  0.53   0.87  0.84  0.51   1.35  0.74     1.25
9            1.13  0.80  1.93  1.00   1.80  1.13  0.68   1.82  1.03     1.71
10           1.87  1.33  3.20  1.67   3.00  1.54  1.04   2.58  1.41     2.44
11           2.00  1.47  3.47  2.00   3.47  1.37  1.02   2.39  1.32     2.34

[12 rows x 32 columns]
***************************
4
   Unnamed: 0_level_0 Unnamed: 1_level_0 Playing Time                     \
                Squad               # Pl           MP Starts   Min   90s
0             Arsenal                  2           15     15  1350  15.0
1         Aston Villa                  2           15     15  1350  15.0
2            Brighton                  2           15     15  1350  15.0
3        Bristol City                  5           15     15  1350  15.0
4             Chelsea                  3           15     15  1350  15.0
5             Everton                  2           15     15  1350  15.0
6      Leicester City                  2           15     15  1350  15.0
7           Liverpool                  2           15     15  1350  15.0
8     Manchester City                  1           15     15  1350  15.0
9      Manchester Utd                  1           15     15  1350  15.0
10          Tottenham                  2           15     15  1350  15.0
11           West Ham                  2           15     15  1350  15.0

   Performance                   ...                     Penalty Kicks      \
            GA  GA90 SoTA Saves  ...   W  D   L CS   CS%         PKatt PKA
0           14  0.93   38    24  ...  11  1   3  4  26.7             1   1
1           31  2.07   82    52  ...   5  1   9  3  20.0             2   2
2           33  2.20   95    62  ...   4  2   9  1   6.7             0   0
3           45  3.00  112    68  ...   1  3  11  0   0.0             2   2
4           13  0.87   59    47  ...  12  1   2  7  46.7             1   1
5           27  1.80   93    65  ...   4  2   9  3  20.0             3   2
6           30  2.00  100    70  ...   4  4   7  2  13.3             2   1
7           20  1.33   58    39  ...   7  4   4  4  26.7             2   2
8            9  0.60   51    41  ...  12  1   2  7  46.7             2   1
9           19  1.27   62    45  ...   7  4   4  5  33.3             2   2
10          29  1.93   72    44  ...   5  4   6  1   6.7             3   3
11          30  2.00   80    49  ...   3  3   9  1   6.7             1   0


   PKsv PKm  Save%
0     0   0    0.0
1     0   0    0.0
2     0   0    NaN
3     0   0    0.0
4     0   0    0.0
5     1   0   33.3
6     1   0   50.0
7     0   0    0.0
8     1   0   50.0
9     0   0    0.0
10    0   0    0.0
11    1   0  100.0

[12 rows x 21 columns]
***************************
5
    Unnamed: 0_level_0 Unnamed: 1_level_0 Playing Time                     \
                 Squad               # Pl           MP Starts   Min   90s
0           vs Arsenal                  2           15     15  1350  15.0
1       vs Aston Villa                  2           15     15  1350  15.0
2          vs Brighton                  2           15     15  1350  15.0
3      vs Bristol City                  5           15     15  1350  15.0
4           vs Chelsea                  3           15     15  1350  15.0
5           vs Everton                  2           15     15  1350  15.0
6    vs Leicester City                  2           15     15  1350  15.0
7         vs Liverpool                  2           15     15  1350  15.0
8   vs Manchester City                  1           15     15  1350  15.0
9    vs Manchester Utd                  1           15     15  1350  15.0
10        vs Tottenham                  2           15     15  1350  15.0
11         vs West Ham                  2           15     15  1350  15.0

   Performance                   ...                     Penalty Kicks      \
            GA  GA90 SoTA Saves  ...   W  D   L CS   CS%         PKatt PKA
0           33  2.20   86    53  ...   3  1  11  2  13.3             3   2
1           19  1.27   76    58  ...   9  1   5  2  13.3             3   3
2           20  1.33   57    37  ...   9  2   4  7  46.7             1   1
3           20  1.33   47    27  ...  11  3   1  4  26.7             2   2
4           45  3.00  118    74  ...   2  1  12  1   6.7             2   2
5           13  0.87   47    34  ...   9  2   4  5  33.3             3   2
6           21  1.40   63    42  ...   7  4   4  4  26.7             0   0
7           22  1.47   57    37  ...   4  4   7  2  13.3             0   0
8           38  2.53  117    79  ...   2  1  12  1   6.7             3   1
9           32  2.13   93    61  ...   4  4   7  0   0.0             1   1
10          21  1.40   87    66  ...   6  4   5  4  26.7             0   0
11          16  1.07   54    38  ...   9  3   3  6  40.0             3   3


   PKsv PKm Save%
0     1   0  33.3
1     0   0   0.0
2     0   0   0.0
3     0   0   0.0
4     0   0   0.0
5     1   0  33.3
6     0   0   NaN
7     0   0   NaN
8     2   0  66.7
9     0   0   0.0
10    0   0   NaN
11    0   0   0.0

[12 rows x 21 columns]
***************************
6
   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Goals            \
                Squad               # Pl                90s    GA PKA FK CK
0             Arsenal                  2               15.0    14   1  0  3
1         Aston Villa                  2               15.0    31   2  0  5
2            Brighton                  2               15.0    33   0  1  7
3        Bristol City                  5               15.0    45   2  1  9
4             Chelsea                  3               15.0    13   1  0  1
5             Everton                  2               15.0    27   2  0  1
6      Leicester City                  2               15.0    30   1  0  4
7           Liverpool                  2               15.0    20   2  0  3
8     Manchester City                  1               15.0     9   1  0  1
9      Manchester Utd                  1               15.0    19   2  0  2
10          Tottenham                  2               15.0    29   3  0  3
11           West Ham                  2               15.0    30   0  0  6

      Expected           ... Passes Goal Kicks                Crosses      \
   OG     PSxG PSxG/SoT  ... AvgLen        Att Launch% AvgLen     Opp Stp
0   0     11.3     0.27  ...   24.7         68    42.6   31.9     139  20
1   1     24.1     0.28  ...   28.7        117    28.2   27.1     233  17
2   0     27.7     0.30  ...   24.8        145    51.7   35.4     264  11
3   1     32.0     0.27  ...   18.0        145    38.6   32.3     292  14
4   1     14.6     0.24  ...   30.3         73    26.0   26.6     138  13
5   0     26.6     0.26  ...   27.2        128    27.3   24.3     228  11
6   1     29.0     0.27  ...   25.0        109    25.7   26.1     204  14
7   1     18.4     0.28  ...   26.9        107    50.5   37.0     244   7
8   0     14.6     0.26  ...   30.2         67    41.8   31.2     134  10
9   2     19.0     0.28  ...   24.3         87    32.2   27.4     155   6
10  1     24.5     0.31  ...   23.5        132    24.2   24.1     241  11
11  0     24.7     0.30  ...   29.6        150    28.7   29.9     205   9

         Sweeper
    Stp%    #OPA #OPA/90 AvgDist
0   14.4      16    1.07    15.8
1    7.3       5    0.33     8.3
2    4.2       8    0.53     4.0
3    4.8       8    0.53    16.0
4    9.4      20    1.33    15.4
5    4.8      11    0.73    26.4
6    6.9      20    1.33    17.3
7    2.9       6    0.40     8.0
8    7.5      13    0.87    16.4
9    3.9      17    1.13    14.3
10   4.6       5    0.33    11.1
11   4.4      21    1.40    18.4

[12 rows x 28 columns]
***************************
7
    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Goals            \
                 Squad               # Pl                90s    GA PKA FK CK
0           vs Arsenal                  2               15.0    33   2  0  5
1       vs Aston Villa                  2               15.0    19   3  0  6
2          vs Brighton                  2               15.0    20   1  0  5
3      vs Bristol City                  5               15.0    20   2  1  3
4           vs Chelsea                  3               15.0    45   2  0  5
5           vs Everton                  2               15.0    13   2  0  4
6    vs Leicester City                  2               15.0    21   0  0  2
7         vs Liverpool                  2               15.0    22   0  0  2
8   vs Manchester City                  1               15.0    38   1  0  4
9    vs Manchester Utd                  1               15.0    32   1  0  6
10        vs Tottenham                  2               15.0    21   0  1  2
11         vs West Ham                  2               15.0    16   3  0  1

      Expected           ... Passes Goal Kicks                Crosses      \
   OG     PSxG PSxG/SoT  ... AvgLen        Att Launch% AvgLen     Opp Stp
0   1     28.3     0.30  ...   29.7        141    32.6   30.4     283  11
1   1     19.7     0.23  ...   29.1        123    28.5   29.3     241   7
2   0     19.1     0.32  ...   26.4        104    19.2   24.7     196   9
3   0     13.5     0.25  ...   25.3         82    31.7   31.2     142  12
4   1     43.9     0.36  ...   29.8        140    46.4   35.0     245  13
5   1     13.7     0.23  ...   27.7         72    33.3   29.5     141  11
6   0     19.3     0.31  ...   31.1         99    41.4   29.6     161   9
7   2     17.7     0.31  ...   30.8        108    50.0   32.4     237  15
8   2     31.7     0.25  ...   26.5        123    26.8   25.7     274  13
9   0     27.4     0.29  ...   30.5        125    42.4   29.7     211  14
10  0     18.5     0.22  ...   26.4         99    27.3   27.5     169  12
11  0     13.7     0.20  ...   26.4        112    32.1   27.7     177  17

        Sweeper
   Stp%    #OPA #OPA/90 AvgDist
0   3.9      11    0.73    11.1

In [25]:
df[0]

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Chelsea,15,12,1,2,45,13,32,37,2.47,37.5,13.6,24.0,1.60,W W W L W,4637,Lauren James - 12,Hannah Hampton,NaN
1,2,Manchester City,15,12,1,2,38,9,29,37,2.47,29.5,12.6,16.8,1.12,W W W W W,3114,Khadija Shaw - 15,Khiara Keating,NaN
2,3,Arsenal,15,11,1,3,33,14,19,34,2.27,34.7,10.9,23.7,1.58,W W L W W,35006,Alessia Russo - 6,Manuela Zinsberger,NaN
3,4,Manchester Utd,15,7,4,4,32,19,13,25,1.67,26.4,17.0,9.4,0.63,L W W L D,11134,Nikita Parris - 8,Mary Earps,NaN
4,5,Liverpool,15,7,4,4,22,20,2,25,1.67,16.4,19.6,-3.2,-0.21,L L D W W,5229,"Sophie Román Haug, Marie-Therese Höbinger - 4",Rachael Laws,NaN
5,6,Tottenham,15,5,4,6,21,29,-8,19,1.27,16.6,23.1,-6.5,-0.44,W L D L L,3902,Martha Thomas - 7,Rebecca Spencer,NaN
6,7,Leicester City,15,4,4,7,21,30,-9,16,1.07,17.3,29.8,-12.5,-0.84,L W L W L,1531,Jutta Rantala - 5,Janina Leitzig,NaN
7,8,Aston Villa,15,5,1,9,19,31,-12,16,1.07,18.7,23.9,-5.2,-0.35,W L D W L,4379,Rachel Daly - 6,Daphne van Domselaar,NaN
8,9,Brighton,15,4,2,9,20,33,-13,14,0.93,14.2,29.9,-15.7,-1.05,W L L L W,3494,Elisabeth Terland - 11,Sophie Baggaley,NaN
9,10,Everton,15,4,2,9,13,27,-14,14,0.93,14.4,25.0,-10.5,-0.70,L L L W L,1011,"Aurora Galli, Megan Finnigan - 3",Courtney Brosnan,NaN
10,11,West Ham,15,3,3,9,16,30,-14,12,0.80,16.4,20.6,-4.2,-0.28,L W W L D,4479,Viviane Asseyi - 6,Mackenzie Arnold,NaN
11,12,Bristol City,15,1,3,11,20,45,-25,6,0.40,12.4,28.5,-16.1,-1.07,L L D L L,7687,Amalie Thestrup - 9,Olivia Clark,NaN

In [26]:
# rename df[0] to highlight it's the current WSL league table

league_table_df = df[0]
league_table_df

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Chelsea,15,12,1,2,45,13,32,37,2.47,37.5,13.6,24.0,1.60,W W W L W,4637,Lauren James - 12,Hannah Hampton,NaN
1,2,Manchester City,15,12,1,2,38,9,29,37,2.47,29.5,12.6,16.8,1.12,W W W W W,3114,Khadija Shaw - 15,Khiara Keating,NaN
2,3,Arsenal,15,11,1,3,33,14,19,34,2.27,34.7,10.9,23.7,1.58,W W L W W,35006,Alessia Russo - 6,Manuela Zinsberger,NaN
3,4,Manchester Utd,15,7,4,4,32,19,13,25,1.67,26.4,17.0,9.4,0.63,L W W L D,11134,Nikita Parris - 8,Mary Earps,NaN
4,5,Liverpool,15,7,4,4,22,20,2,25,1.67,16.4,19.6,-3.2,-0.21,L L D W W,5229,"Sophie Román Haug, Marie-Therese Höbinger - 4",Rachael Laws,NaN
5,6,Tottenham,15,5,4,6,21,29,-8,19,1.27,16.6,23.1,-6.5,-0.44,W L D L L,3902,Martha Thomas - 7,Rebecca Spencer,NaN
6,7,Leicester City,15,4,4,7,21,30,-9,16,1.07,17.3,29.8,-12.5,-0.84,L W L W L,1531,Jutta Rantala - 5,Janina Leitzig,NaN
7,8,Aston Villa,15,5,1,9,19,31,-12,16,1.07,18.7,23.9,-5.2,-0.35,W L D W L,4379,Rachel Daly - 6,Daphne van Domselaar,NaN
8,9,Brighton,15,4,2,9,20,33,-13,14,0.93,14.2,29.9,-15.7,-1.05,W L L L W,3494,Elisabeth Terland - 11,Sophie Baggaley,NaN
9,10,Everton,15,4,2,9,13,27,-14,14,0.93,14.4,25.0,-10.5,-0.70,L L L W L,1011,"Aurora Galli, Megan Finnigan - 3",Courtney Brosnan,NaN
10,11,West Ham,15,3,3,9,16,30,-14,12,0.80,16.4,20.6,-4.2,-0.28,L W W L D,4479,Viviane Asseyi - 6,Mackenzie Arnold,NaN
11,12,Bristol City,15,1,3,11,20,45,-25,6,0.40,12.4,28.5,-16.1,-1.07,L L D L L,7687,Amalie Thestrup - 9,Olivia Clark,NaN

In [27]:
# above table can now be used for analysis
# for example, return the WSL team with the highest attendance this season

team_with_highest_attendance = league_table_df['Attendance'].idxmax()

team_name = league_table_df.loc[team_with_highest_attendance, 'Squad']
highest_attendance = league_table_df.loc[team_with_highest_attendance, 'Attendance']

print("Team with the highest attendance:", team_name)
print("Attendance:", highest_attendance)

Team with the highest attendance: Arsenal
Attendance: 35006